# Generated by Django 4.1.7 on 2023-09-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField()),
                ('cycles', models.IntegerField()),
                ('kWh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hisytory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('half', models.IntegerField()),
                ('name', models.TextField()),
                ('no_available', models.IntegerField()),
                ('no_slots', models.IntegerField()),
                ('ready', models.IntegerField()),
            ],
        ),
    ]
