# Generated by Django 4.1.5 on 2023-09-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hisytory',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='half',
            new_name='avail_slots',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='no_available',
            new_name='battery_available',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='no_slots',
            new_name='battery_half',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='ready',
            new_name='battery_ready',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='name',
            new_name='stationname',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='kWh',
        ),
        migrations.RemoveField(
            model_name='station',
            name='sid',
        ),
        migrations.AddField(
            model_name='battery',
            name='batteryid',
            field=models.TextField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battery',
            name='power',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battery',
            name='stationid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battery',
            name='status',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='stationid',
            field=models.TextField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battery',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
