# Generated by Django 4.1.5 on 2023-09-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_hisytory_rename_half_station_avail_slots_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
